baseURL = "http://example.org/"
languageCode = "en-us"
title = "Urca Process"
theme = "hello-friend"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

[languages]
  [languages.en]
    title = "Urca Process"
    subtitle = "A Math and Science blog"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"

    [languages.en.params.logo]
      logoText = "Urca Process"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/main/about"
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact Me"
        url = "/main/contact"
        

